# Generated by Django 6.0.6 on 2026-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('sal', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
